/* eslint-disable */
// @ts-nocheck
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async listProjects() : Promise<Result<ProjectSummary[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_projects") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listSessions(projectId: string) : Promise<Result<SessionMeta[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_sessions", { projectId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSession(projectId: string, sessionId: string) : Promise<Result<SessionDetail, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_session", { projectId, sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getPricing() : Promise<PricingTable> {
    return await TAURI_INVOKE("get_pricing");
}
}

/** user-defined events **/


export const events = __makeEvents__<{
sessionsChanged: SessionsChanged
}>({
sessionsChanged: "sessions-changed"
})

/** user-defined constants **/



/** user-defined types **/

export type Block = { type: "text"; text: string } | { type: "thinking"; thinking: string } | { type: "tool_use"; id: string; name: string; input: JsonValue; result: ToolResultInfo | null } | 
/**
 * A tool result whose tool_use was never seen (kept unpaired).
 */
{ type: "tool_result"; tool_use_id: string; is_error: boolean; content: string }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
export type Message = { 
/**
 * Line uuid; None when the CLI omitted it.
 */
uuid: string | null; 
/**
 * API message id (shared by streamed chunks of one assistant turn).
 */
message_id: string | null; role: string; timestamp: string | null; model: string | null; usage: TokenUsage | null; blocks: Block[] }
/**
 * USD per 1M tokens for one model family, matched by substring on the model id.
 */
export type ModelPricing = { model_match: string; input: number; output: number; cache_creation: number; cache_read: number }
/**
 * Hardcoded approximate rates. Labeled estimated: rates drift and are not
 * fetched live; the UI must present costs as estimates.
 */
export type PricingTable = { rates: ModelPricing[]; default_model_match: string; disclaimer: string }
export type ProjectSummary = { project_id: string; name: string; path: string; session_count: number; active_count: number }
export type SessionDetail = { meta: SessionMeta; messages: Message[]; malformed_lines: number }
export type SessionMeta = { session_id: string; project_id: string; started_at: string | null; ended_at: string | null; message_count: number; tokens: TokenUsage; estimated_cost_usd: number; models: string[]; cli_version: string | null; git_branch: string | null; cwd: string | null; preview: string; is_active: boolean }
export type SessionsChanged = { kind: string; project_id: string; session_id: string | null }
export type TokenUsage = { input_tokens: number; output_tokens: number; cache_creation_input_tokens: number; cache_read_input_tokens: number }
export type ToolResultInfo = { is_error: boolean; content: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
