import { describe, expect, it } from "vitest";
import { parseUserText } from "./command-tags";

describe("parseUserText", () => {
  it("passes plain text through", () => {
    expect(parseUserText("hello world")).toEqual([
      { kind: "text", text: "hello world" },
    ]);
  });

  it("builds a command chip from name + args", () => {
    expect(
      parseUserText(
        "<command-name>/cook</command-name><command-args>plan.md --fast</command-args>",
      ),
    ).toEqual([{ kind: "command", name: "/cook", args: "plan.md --fast" }]);
  });

  it("turns local stdout into a terminal segment and drops the caveat", () => {
    const raw =
      "<local-command-caveat>generated by local commands</local-command-caveat>" +
      "<command-name>/clear</command-name>" +
      "<local-command-stdout>cleared 3 files</local-command-stdout>";
    expect(parseUserText(raw)).toEqual([
      { kind: "command", name: "/clear", args: "" },
      { kind: "stdout", text: "cleared 3 files" },
    ]);
  });

  it("keeps surrounding plain text in order", () => {
    const raw = "before <command-name>/x</command-name> after";
    expect(parseUserText(raw)).toEqual([
      { kind: "text", text: "before" },
      { kind: "command", name: "/x", args: "" },
      { kind: "text", text: "after" },
    ]);
  });

  it("survives an unterminated tag", () => {
    expect(parseUserText("<local-command-stdout>tail without close")).toEqual([
      { kind: "stdout", text: "tail without close" },
    ]);
  });
});
